[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "mpi4py",
    "Cython",  # Ensure Cython is included as a build dependency
    "numpy"    # It's often necessary to include numpy if using it in setup.py
]
build-backend = "setuptools.build_meta"
